CREATE TABLE IF NOT EXISTS VideoData
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Title VARCHAR(100) NOT NULL,
	Description TEXT NOT NULL,
	Channel VARCHAR(20) NOT NULL,
	Views LONG NOT NULL,
	Likes INTEGER,
	Dislikes INTEGER,
	Length INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Videos
(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	VideoID VARCHAR(11) NOT NULL UNIQUE,
	VideoDataID INTEGER REFERENCES VideoData(ID)
);